services:
  app:
    build: .
    container_name: "coxit_docs_search_mcp"
    env_file:
      - .env
    ports:
      - "8011:8011"
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./files:/app/files
      - ./telemetry:/app/telemetry
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: "redis/redis-stack:latest"
    container_name: "coxit_docs_redis"
    expose:
      - "6379"
    volumes:
      - ./redis-data:/data
    restart: unless-stopped
