name: Try Deploy pdf-chat

on:
  workflow_dispatch:
#  pull_request:
#    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Compose stack
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: docker compose -f docker-compose-stack-dev.yaml up -d

      - name: Wait for services to be ready
        run: sleep 60

      - name: Check if services are running
        run: docker compose -f docker-compose-stack-dev.yaml ps
